// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/isaacRevan24/fitness-tracking/model"
)

// MockTrackingHandlerInterface is a mock of TrackingHandlerInterface interface.
type MockTrackingHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingHandlerInterfaceMockRecorder
}

// MockTrackingHandlerInterfaceMockRecorder is the mock recorder for MockTrackingHandlerInterface.
type MockTrackingHandlerInterfaceMockRecorder struct {
	mock *MockTrackingHandlerInterface
}

// NewMockTrackingHandlerInterface creates a new mock instance.
func NewMockTrackingHandlerInterface(ctrl *gomock.Controller) *MockTrackingHandlerInterface {
	mock := &MockTrackingHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockTrackingHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackingHandlerInterface) EXPECT() *MockTrackingHandlerInterfaceMockRecorder {
	return m.recorder
}

// AddWeightRegister mocks base method.
func (m *MockTrackingHandlerInterface) AddWeightRegister(request model.AddWeightRegisterReq) model.FitnessResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWeightRegister", request)
	ret0, _ := ret[0].(model.FitnessResponse)
	return ret0
}

// AddWeightRegister indicates an expected call of AddWeightRegister.
func (mr *MockTrackingHandlerInterfaceMockRecorder) AddWeightRegister(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWeightRegister", reflect.TypeOf((*MockTrackingHandlerInterface)(nil).AddWeightRegister), request)
}

// DeleteWeightRegister mocks base method.
func (m *MockTrackingHandlerInterface) DeleteWeightRegister(request model.DeleteWeightRegisterReq) model.FitnessResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWeightRegister", request)
	ret0, _ := ret[0].(model.FitnessResponse)
	return ret0
}

// DeleteWeightRegister indicates an expected call of DeleteWeightRegister.
func (mr *MockTrackingHandlerInterfaceMockRecorder) DeleteWeightRegister(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWeightRegister", reflect.TypeOf((*MockTrackingHandlerInterface)(nil).DeleteWeightRegister), request)
}

// GetWeightRegister mocks base method.
func (m *MockTrackingHandlerInterface) GetWeightRegister(clientId, weightId string) model.FitnessResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeightRegister", clientId, weightId)
	ret0, _ := ret[0].(model.FitnessResponse)
	return ret0
}

// GetWeightRegister indicates an expected call of GetWeightRegister.
func (mr *MockTrackingHandlerInterfaceMockRecorder) GetWeightRegister(clientId, weightId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeightRegister", reflect.TypeOf((*MockTrackingHandlerInterface)(nil).GetWeightRegister), clientId, weightId)
}

// UpdateWeightRegister mocks base method.
func (m *MockTrackingHandlerInterface) UpdateWeightRegister(request model.UpdateWeightRegisterReq) model.FitnessResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWeightRegister", request)
	ret0, _ := ret[0].(model.FitnessResponse)
	return ret0
}

// UpdateWeightRegister indicates an expected call of UpdateWeightRegister.
func (mr *MockTrackingHandlerInterfaceMockRecorder) UpdateWeightRegister(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWeightRegister", reflect.TypeOf((*MockTrackingHandlerInterface)(nil).UpdateWeightRegister), request)
}

// MockGoalsHandlerInterface is a mock of GoalsHandlerInterface interface.
type MockGoalsHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGoalsHandlerInterfaceMockRecorder
}

// MockGoalsHandlerInterfaceMockRecorder is the mock recorder for MockGoalsHandlerInterface.
type MockGoalsHandlerInterfaceMockRecorder struct {
	mock *MockGoalsHandlerInterface
}

// NewMockGoalsHandlerInterface creates a new mock instance.
func NewMockGoalsHandlerInterface(ctrl *gomock.Controller) *MockGoalsHandlerInterface {
	mock := &MockGoalsHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockGoalsHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoalsHandlerInterface) EXPECT() *MockGoalsHandlerInterfaceMockRecorder {
	return m.recorder
}

// AddGoalsRegister mocks base method.
func (m *MockGoalsHandlerInterface) AddGoalsRegister(request model.AddWeightGoalsReq) model.FitnessResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGoalsRegister", request)
	ret0, _ := ret[0].(model.FitnessResponse)
	return ret0
}

// AddGoalsRegister indicates an expected call of AddGoalsRegister.
func (mr *MockGoalsHandlerInterfaceMockRecorder) AddGoalsRegister(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGoalsRegister", reflect.TypeOf((*MockGoalsHandlerInterface)(nil).AddGoalsRegister), request)
}

// GetGoalsRegister mocks base method.
func (m *MockGoalsHandlerInterface) GetGoalsRegister(request model.GetGoalsReq) model.FitnessResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoalsRegister", request)
	ret0, _ := ret[0].(model.FitnessResponse)
	return ret0
}

// GetGoalsRegister indicates an expected call of GetGoalsRegister.
func (mr *MockGoalsHandlerInterfaceMockRecorder) GetGoalsRegister(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoalsRegister", reflect.TypeOf((*MockGoalsHandlerInterface)(nil).GetGoalsRegister), request)
}
